### ISSUE TITLE
tee::system2 broken if echo empty line

### ISSUE THREAD

**Issue by jcubic** [pycontribs/tendo#25]
Executing this script display no output:

```python
#!/usr/bin/env python
print '''
Waiting for verification...
Cleaning up challenges
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/www.domektkaczki.pl/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/www.domektkaczki.pl/privkey.pem
   Your cert will expire on 2018-06-08. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - If you like Certbot, please consider supporting our work by:
'''
```
because first line is empty.

**Comment by jcubic** [comment]
the problem is `line = line.rstrip('\n\r')` it need to be after:

```
if not line:
            break
```

the readline return empty string on EOF but in this case it return "\n" and got removed and script ends.

**Comment by ssbarnea** [comment]
Can you please write a small example the reproduces the bug? Like a call to `system2()`. I tried to reproduce the problem myself and failed.

**Comment by jcubic** [comment]
Sorry it's seems to work but on windows it take several seconds to execute the script, on linux it's instant.

**Comment by ssbarnea** [comment]
@jcubic I can only feel sorry for you having to use Windows. ;)

**Comment by jcubic** [comment]
I use mainly GNU/Linux but needed to rewrite some bash script for windows that have linux tee command in it.
