### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by picibucor** [pycontribs/tendo#29]
Windows 7
Python 3.6
tendo 0.2.12
Pyinstaller 3.4.dev0+b31794cf1

Hey all,

after updating tendo I created an .exe with Pyinstaller. 

Trying to run my .exe gives the following error-message:
> [WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "site-packages\pbr\version.py", line 442, in _get_version_from_pkg_resources
[WARNING] stderr:   File "site-packages\pkg_resources\__init__.py", line 344, in get_provider
[WARNING] stderr:   File "site-packages\pkg_resources\__init__.py", line 892, in require
[WARNING] stderr:   File "site-packages\pkg_resources\__init__.py", line 778, in resolve
[WARNING] stderr: pkg_resources.DistributionNotFound: The 'tendo' distribution was not found and is required by the application
[WARNING] stderr: 
[WARNING] stderr: During handling of the above exception, another exception occurred:
[WARNING] stderr: 
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "to_exe\main.py", line 79, in <module>
[WARNING] stderr:     from tendo import singleton
[WARNING] stderr:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[WARNING] stderr:   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
[WARNING] stderr:   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
[WARNING] stderr:   File "c:\users\mirk\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 628, in exec_module
[WARNING] stderr:     exec(bytecode, module.__dict__)
[WARNING] stderr:   File "site-packages\tendo\__init__.py", line 10, in <module>
[WARNING] stderr:   File "site-packages\pbr\version.py", line 462, in semantic_version
[WARNING] stderr:   File "site-packages\pbr\version.py", line 449, in _get_version_from_pkg_resources
[WARNING] stderr:   File "site-packages\pbr\packaging.py", line 816, in get_version
[WARNING] stderr: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name tendo was given, but was not able to be found.

**Comment by marunguy** [comment]
* Windows 8.1 64bit, Python 2.7.15 32bit, tendo 0.2.12, pbr 4.0.2, pyinstaller 3.3.1, py2exe 0.6.10a1

I have a same problem.
Can the use of pbr package be avoided?
The pbr package may not compatible to pyinstaller and py2exe.
https://github.com/pycontribs/tendo/commit/614ad535cddf08fb568933e5f3174b3788f95c26#diff-897bd04780b3507bca0f1da6caff74fd
https://github.com/pyinstaller/pyinstaller/issues/2868
https://stackoverflow.com/questions/46369902/how-to-package-tensorflow-with-pyinstaller-on-macosx

Below is the test code for workaround.
When freezed, version information is incorrect.
```python
# test.py
import os
os.environ["PBR_VERSION"] = "4.0.2"
import tendo
print tendo.__version__
```
```
D:\\test>test.py
0.2.12
D:\\test\\dist\\test.exe
4.0.2
```

**Comment by ssbarnea** [comment]
I do no want to get rid of `pbr` usage, so if there is a bug in it, feel free to raise a CRs to fix it and I will be more than happy to bump its version.

**Comment by Keramatfar** [comment]
Project name pybliometrics was given, but was not able to be found.

**Comment by BoboTiG** [comment]
FTR I could fix the issue without hook: https://github.com/BoboTiG/watermark-me/commit/bf5f533af7097533e257c58cd7a84ebc302899ee
