### ISSUE TITLE
Wrong use of __del__ method.

### ISSUE THREAD

**Issue by lunemec** [pycontribs/tendo#31]
I ran across this library [while searching for a library to provide me with fs locking mechanism to run program once](https://stackoverflow.com/questions/380870/python-single-instance-of-program).

However, the script uses `__del__` method, which is incorrect: https://github.com/pycontribs/tendo/blob/master/tendo/singleton.py#L71 

From [python docs](https://docs.python.org/3/reference/datamodel.html#object.__del__): 

> It is not guaranteed that __del__() methods are called for objects that still exist when the interpreter exits.

Which would cause it to be locked forever.

**Comment by ssbarnea** [comment]
@lunemec AFAIK, the kernel will release the lock when process exists anyway. I will consider this not a bug unless you are able to find a way to reproduce that behavior.
