### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by BoboTiG** [pycontribs/tendo#32]
Hello,

It would be very cool to have a new release for the `SingleInstance(lockfile)` new feature :)

**Comment by pinkynrg** [comment]
I don't understand, is this a compatibility issue with the past release on pypi? 

Wouldn't it be possible to just change the name of the package?

I would like to use the newer version too, but I don't like the idea to copy and paste the code from the repo.

**Comment by ssbarnea** [comment]
Released made few moments ago https://pypi.org/project/tendo/0.2.15/
