### ISSUE TITLE
logger.error vs logger.warning

### ISSUE THREAD

**Issue by kentavv** [pycontribs/tendo#35]
On win32 logger.error is used else logger.warning is used. Perhaps select the same for both platforms?

https://github.com/pycontribs/tendo/blob/56c9a6f09339e61fac1e93e93fbdb3efd7cad54a/tendo/singleton.py#L54

**Comment by danielferber** [comment]
I agree. I would also prefer the behavior proposed by @kentavv .

**Comment by ssbarnea** [comment]
If you want to have it fixed, please make a PR.
