### ISSUE TITLE
Is necessary to include 'quitting' in log message?

### ISSUE THREAD

**Issue by kentavv** [pycontribs/tendo#36]
Some may want to catch the exception instead and not quit. Perhaps the logger message should not include 'quitting' in the message.

https://github.com/pycontribs/tendo/blob/56c9a6f09339e61fac1e93e93fbdb3efd7cad54a/tendo/singleton.py#L54

**Comment by danielferber** [comment]
I agree. I would also prefer the behavior proposed by @kentavv .

**Comment by ssbarnea** [comment]
Exiting is by design, in order to avoid running the script twice.

**Comment by kentavv** [comment]
Sorry, my suggestion here, similar to #35, was likely unclear. I meant to say that: some may wish to catch the exception and gracefully handle shutdown quietly, without the "quitting" message to stdout.
