### ISSUE TITLE
Window flashing when packaged with PyInstaller.

### ISSUE THREAD

**Issue by sobir-git** [pycontribs/tendo#37]
I put the example code (from singleton module) at the top of my script and it worked as expected. But when I converted it to .exe with PyInstaller the .exe also works fine and prevents multiple instances of my program, except there are some windows flashing before the program starts. 
I guess this is the multiprocessing issue as always it flashes new windows in .exe files. So I removed the multiprocessing imports and usages from singleton.py and the window flashing was gone.

I think someone should prevent unitTests from running multiprocessing in .exe mode.

**Comment by ssbarnea** [comment]
Unrelated to tendo itself.
