### ISSUE TITLE
SingleInstance prints log messages twice

### ISSUE THREAD

**Issue by danielferber** [pycontribs/tendo#39]
While testing the script that uses SingleInstance, I noticed that log messagaes from SingleInstance are printed twice. I think this behavior relates to the StreamHandler added at line
https://github.com/pycontribs/tendo/blob/b1e08eb8e3e5f259ad75a4c0f3cfb2cac02aeac9/tendo/singleton.py#L144

I would suggest moving this line into the 'if __name__ == "__main__":', so that the  StreamHandler  will be created and used only within the unit tests as I think it was expected.

**Comment by ssbarnea** [comment]
True. Please make a PR and I gladly merge it.

**Comment by danielferber** [comment]
I created a pull request. But I did not yet figure out how to prevent the minimal test coverage decrease for the proposed simple change.

**Comment by ssbarnea** [comment]
Fixed and released.
