### ISSUE TITLE
Adding non blocking behavior in locking mechanism

### ISSUE THREAD

**Issue by himanshu219** [pycontribs/tendo#41]
https://github.com/pycontribs/tendo/blob/d3b0e9e8fe5bc390a0bd378bd6ec2d185b5f3cb6/tendo/singleton.py#L53

Is this non blocking I think we need to add os.O_NONBLOCK here as well similar to what we are doing for non windows versions.

**Comment by liorp** [comment]
This API is not available for non UNIX systems - [os docs](https://docs.python.org/3/library/os.html#os.O_NONBLOCK)
