### ISSUE TITLE
BlockingIOError: [Errno 35] Resource temporarily unavailable

### ISSUE THREAD

**Issue by sleekmike** [pycontribs/tendo#43]
Hello, 
I am trying to run a Flask App in which tendo was used, I have installed tendo successfully but when I try to run the app I get the error below:

 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
 * Restarting with stat
Another instance is already running, quitting.
Traceback (most recent call last):
  File "/Users/macbook/Desktop/securityPI/pi/lib/python3.7/site-packages/tendo/singleton.py", line 66, in __init__
    fcntl.lockf(self.fp, fcntl.LOCK_EX | fcntl.LOCK_NB)
BlockingIOError: [Errno 35] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macbook/Desktop/securityPI/prgms/webPrgm.py", line 155, in <module>
    me = singleton.SingleInstance()
  File "/Users/macbook/Desktop/securityPI/pi/lib/python3.7/site-packages/tendo/singleton.py", line 70, in __init__
    raise SingleInstanceException()
tendo.singleton.SingleInstanceException

I am using a Mac running macOS Catalina 10.15 and python3.7

**Comment by sergem155** [comment]
Same issue here, running a script from cron:
`
#!/usr/bin/python3
import traceback
def main(argv=None):
	# ensure single instance
	me = singleton.SingleInstance()
if __name__ == "__main__":
	sys.exit(main())
`

**Comment by ssbarnea** [comment]
I will close this as not being able to reproduce. If you can make a PR that adds a tests that is failing, it would be a good opportunity to reopen the issue.
