### ISSUE TITLE
Compatibility with Python 3.7?

### ISSUE THREAD

**Issue by jehrenzweig** [pycontribs/tendo#44]
The official documentation states that Tendo is compatible with Python 2.7 - 3.6.  Are there any known issues using it with Python 3.7?

**Comment by ssbarnea** [comment]
@jehrenzweig I am no longer using the library and looking to handle it to anyone that wants to maintain it.

The best way to test py37 compatibility is to propose a PR that enables it. It could also be a good start for becoming a maintainer.
