### ISSUE TITLE
💖 looking for maintainers (cores) 

### ISSUE THREAD

**Issue by ssbarnea** [pycontribs/tendo#51]
I am looking for maintainers/core to join this project as I an personally not using it anymore.

I can still keep providing CI/CD support for them.

**Comment by liorp** [comment]
@ssbarnea , I'd be happy to be a maintainer!

**Comment by ssbarnea** [comment]
Hi @liorp! Start doing some pull requests, preferably maintenance and I will help you take-over. Feel free to ask me if you have any questions.

**Comment by ssbarnea** [comment]
@liorp I sent you an invite. I merged the change, even it was too big for my taste. Still as too many things did pile up over the years, it could make sense to bend the rules once.

**Comment by liorp** [comment]
Thanks! Appreciated. Sent from my iPhoneOn 27 Sep 2022, at 23:51, Sorin Sbarnea ***@***.***> wrote:﻿
@liorp I sent you an invite. I merged the change, even it was too big for my taste. Still as too many things did pile up over the years, it could make sense to bend the rules once.
