### ISSUE TITLE
run process in popen and send kill will not remove the lock file

### ISSUE THREAD

**Issue by instasck** [pycontribs/tendo#55]
windows
xxx = 'python_with_singlton.py'
pros = popen(xxx)
pros.kill()
pros = popen(xxx)  - #  PermissionError: [WinError 32] The process cannot access the file because it is being used ....

**Comment by ssbarnea** [comment]
I am no longer using this library, so I could only help with reviewing pull-requests, if they pass CI.

**Comment by liorp** [comment]
Hi, I've tried running your code (both with `os.popen` and `subprocess.Popen`) and it ran successfully.

**Comment by instasck** [comment]
@liorp makore :)?
OK THE ISSUES I FOUND OUT WAS:
I uses a library called sqlitdict it open a connection to database sqlite3
If it does not closes with .close() it will leave the process in memory.
In compare to just closing the cmd windows that closes all the open db access.
