### ISSUE TITLE
singleton.py misdesign

### ISSUE THREAD

**Issue by Ignalion** [pycontribs/tendo#8]
Hello

I've just made the same issue to one project (PyBitMessage) that using your idea. The thing I want to talk aboue is file [singleton.py](https://github.com/pycontribs/tendo/blob/master/tendo/singleton.py) with singleinstance class especially.

The design of this class is incorrect because of two things as below:
1. This class has to ensure that lock file is being deleted when app is closed (as far as I understand it). But it won't work. Well, it would, probably, but as it's stated in python doc, it's not guaranteed that `__del__` method will ever called. So it can easily lead to situation when lock file remains in system after app shutdown.
2. There is `try..except` block in `__del__` method which would not work ever because, as stated in python doc, any exception that occurs while running `__del__` method will be ignored and just printed a warning in stderr instead.

Thus, I'd suggest to either make some other method like `release()` that should be called directly or redesign this class\idea.

Thanks,
Constantine

**Comment by ssbarnea** [comment]
I didn't use the Singleton in a long time but if you make a pull request I will be more than happy to review it and to include it.

**Comment by NadavK** [comment]
By just reviewing the code (not actual testing), Singleton's logic is not based on file EXISTENCE, rather on the file being LOCKED.
I assume the __del__ is just for completeness, and not actually required

**Comment by ssbarnea** [comment]
Yes, that is because a running script can be terminated at any time, failing to remove the file. Due to this, the only way to assure some kind of locking mechanism was to check if the file is locked or not.

/sorin

**Comment by bristea** [comment]
foo
