### ISSUE TITLE
How to Release the lock file before script end ?

### ISSUE THREAD

**Issue by instasck** [pycontribs/tendo#94]
I am looking for a way to sync 2 process using a lock file.
So only one process can run at the same time.
runner_lock_obj = singleton.SingleInstance(lockfile=running_lock_filename)
.. do what ever but here the other file wont run...
runner_lock_obj.__del__()
.. do what ever but here the other file CAN run...

This works nice, just when I get out of the run I get 
```
[Errno 9] Bad file descriptor
Exception ignored in: <function SingleInstance.__del__ at 0x000001ECB2A58670>
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\tendo\singleton.py", line 89, in __del__
SystemExit: -1
```

I guess it already exited ... can IU avoid this error ?

**Comment by ssbarnea** [comment]
Windows is no longer supported.
